[package]
name = "image-to-ascii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
terminal_size = "0.2.1"
crossterm = "0.25.0"

